source 'http://rubygems.org'

gem 'amazon-ecs'
gem 'clockwork'
gem 'delayed_job'
gem 'devise'
gem 'haml-rails'
gem 'hpricot'
gem 'jquery-rails'
gem 'lastfm'
gem 'mysql2'
gem 'metal-archives', '~> 0.2'
gem 'rails'
gem 'rails3-generators'
gem 'ruby_parser'
gem 'state_machine'
gem 'will_paginate', '~> 3.0.pre2'

group :test do
  gem 'factory_girl_rails'
  gem 'rspec-rails'
  gem 'spork', '~> 0.9.0.rc'
  gem 'watchr'
  gem 'webrat'
end
