source 'http://rubygems.org'

gem 'rails'
gem 'mysql2'
gem 'jquery-rails'
gem 'haml-rails'
gem 'will_paginate', '~> 3.0.pre2'
gem 'rails3-generators'
gem 'devise'
gem 'hpricot'
gem 'ruby_parser'
gem 'clockwork'
gem 'delayed_job'
gem 'fastercsv'
gem 'metal-archives', '~> 0.2'
gem 'amazon-ecs'
#gem 'lastfm'
gem 'lastfm', :git => 'git://github.com/dbolson/ruby-lastfm.git', :branch => 'library_get_artists'

group :test do
  gem 'rspec-rails'
  gem 'watchr'
  gem 'spork', '~> 0.9.0.rc'
  gem 'factory_girl_rails'
  gem 'rcov'
end
